live_config_reload = true

import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1

[window.dimensions]
columns = 200
lines = 40

[window.padding]
x = 10
y = 10

[font]
size = 14
